### ISSUE TITLE
Class Files Doesn't Exist

### ISSUE THREAD

**Issue by Milkhan** [dniccum/nova-documentation#1]
Thank you for the nice package! 
But when I tried to install (Nova v1.3.2) but after I ran the 
-composer require dniccum/nova-documentation
got an error:
In Container.php line 779:
  Class files does not exist

**Comment by dniccum** [comment]
Thanks @Milkhan. I just pushed version 1.0.2 with the appropriate fixes. You may need to run `composer update dniccum/nova-documentation` to remove the previous version from your project, and then re-enter `composer require dniccum/nova-documentation`
