### ISSUE TITLE
absolute link

### ISSUE THREAD

**Issue by breizhwave** [dniccum/nova-documentation#10]
Hello I'd like to use absolute links but does not work, always add /documentation : 

* [Import](/nova-vendor/import)

any possibility of using absolute url without specifying root domain ? thks

**Comment by adriaanzon** [comment]
Similar issue here. When I try to add a `mailto` link, it prepends /nova/documentation.

**Comment by dniccum** [comment]
Please see the [version 1.1.1](https://github.com/dniccum/nova-documentation/releases/tag/v1.1.1) release; more specifically [this bit of code](https://github.com/dniccum/nova-documentation/blob/master/src/Library/MarkdownUtility.php#L210). Relative links and mailto links are now supported and should be left alone by the Markdown parser.
