### ISSUE TITLE
Lost some of the styling after updating to v1.1.0

### ISSUE THREAD

**Issue by adriaanzon** [dniccum/nova-documentation#11]
* there is less spacing between headings and paragraphs
* `<a>` tags have a different color
* blockquotes aren't indented
* horizontal rules aren't displayed

Here's a comparison of the included sample.md:

| v1.0.2.2 | v1.1.0 |
| --- | --- |
| <img width="898" alt="Screenshot 2019-11-06 at 20 36 05" src="https://user-images.githubusercontent.com/4326420/68331751-ce748c00-00d5-11ea-87b1-0486bb80a4d1.png"> | <img width="750" alt="Screenshot 2019-11-06 at 20 42 34" src="https://user-images.githubusercontent.com/4326420/68331851-0085ee00-00d6-11ea-81b0-106fd1123107.png"> |

**Comment by adriaanzon** [comment]
I think it might be because of PurgeCSS

**Comment by Razorsheep** [comment]
Great work @adriaanzon. Any chance we can get this PR merged in today @dniccum ?

**Comment by dniccum** [comment]
I will take a look at this one over my lunch and get it merged. Apologies for the delay.

**Comment by Razorsheep** [comment]
Thanks! 😀
