### ISSUE TITLE
Would be nice if this was in the readme file

### ISSUE THREAD

**Issue by ghost** [dniccum/nova-documentation#15]
I was having trouble sorting the sidebar links to my liking.  My solution was to prepend each file name with AAAA or BBBB etc. 

And in the config file change the 'home' => 'documentation/AAAAmyhomefile.md'

Thanks for this easy to use tool.

**Comment by dniccum** [comment]
You can now organize your content by adding YAML configuration to the top of your files. Please see #16, and also see the [upgrade guide](https://github.com/dniccum/nova-documentation#upgrading-from-version-1)
