### ISSUE TITLE
support Nova 4.xx

### ISSUE THREAD

**Issue by newtec-foggia** [dniccum/nova-documentation#19]
is there an update to version 4 of Nova?

**Comment by jimbojsb** [comment]
We'd potentially be willing to sponsor the dev work for this...

**Comment by dniccum** [comment]
@jimbojsb Do you have a timeline of when you need this feature? I might be able to get to it by the end of the year.

**Comment by jimbojsb** [comment]
It's not urgent, we'd just like to have it as we start upgrading our (many) apps to Nova 4.x. Feel free to email me if you'd like to discuss.

**Comment by mstaack** [comment]
highly interested in a v4 version too

**Comment by LoganTFox** [comment]
Any update on this?

**Comment by dniccum** [comment]
@LoganTFox I am actively in flight on this. I hope to have this finished soon.

**Comment by LoganTFox** [comment]
@dniccum awesome thank you!

**Comment by dniccum** [comment]
@newtec-foggia @mstaack @LoganTFox @jimbojsb  Nova 4 support has been added with #21.

**Comment by LoganTFox** [comment]
Thank you very much for your hard work!
