### ISSUE TITLE
Can't find the documentation files

### ISSUE THREAD

**Issue by LoganTFox** [dniccum/nova-documentation#24]
I have upgraded to the new version and I'm using the package with Nova 4. I have everything setup like the documentation says and I'm pointing it to my home page.

It seems to find the file as I can see the contents in the error but I can't figure out why it won't render properly. I've cleared all my cache and everything.

Any ideas?

<img width="898" alt="Screen Shot 2023-02-06 at 3 55 41 PM" src="https://user-images.githubusercontent.com/31284288/217096697-872e9b83-a9b0-4ad8-bb3f-d02e6556b952.png">

**Comment by LoganTFox** [comment]
My fault. It had the wrong parser set.

**Comment by LoganTFox** [comment]
I am able to get this working by switching to the YAML configuration and added the proper fields but the markdown configuration doesn't seem to work.

**Comment by dniccum** [comment]
@LoganTFox I have been able to replicate this locally. I am working on a fix.

**Comment by LoganTFox** [comment]
Thank you!
