### ISSUE TITLE
Package doesn't correctly handle custom nova.path

### ISSUE THREAD

**Issue by dm-pf** [dniccum/nova-documentation#26]
Hi,

_I believe this might be a regression caused by PR #25 , but cannot be sure because it's our first time using this package._

We have a custom nova.path as follows: `config/nova.php : path => '/'` so one would expect the package to be available at `example.com/documentation` but it is rather available at `example.com/nova/documentation`. 

## Bad sidenav link

The sidenav link is [correctly set as `/documentation`](https://github.com/dniccum/nova-documentation/blob/f8b488d6ac23e5ef2c0d58f790f8ee10ec4cba66/src/NovaDocumentation.php#L40) but when clicked it hits a 404 error.

`artisan route:list` shows:

![Screenshot 2023-02-23 at 15 03 33](https://user-images.githubusercontent.com/100700999/220929891-dd3edffd-9869-4857-8b24-33bc564ec542.png)

Which is caused by [hardcoding the 'nova' path in the router](https://github.com/dniccum/nova-documentation/blob/f8b488d6ac23e5ef2c0d58f790f8ee10ec4cba66/src/ToolServiceProvider.php#L89). By removing 'nova/' from the router prefix the url is back to what one expects it to be, and the sidebar link works again.

## Bad internal documentation links

Internal documentation links are also not handled properly probably because the package doesn't expect `nova.path` to end in `/`:
![image](https://user-images.githubusercontent.com/100700999/220932553-4e727b11-b6b2-44a9-8e73-d6ac3f663033.png)

_Btw, `href="//documentation/sample"` generates: `https://documentation/sample`_

Contents section links are not handled at all, probably because [the regex didn't find what it expected](https://github.com/dniccum/nova-documentation/blob/2fc704408df5bd3638167b06de52450d280543f2/src/Library/Contracts/DocumentationPage.php#L85):
![image](https://user-images.githubusercontent.com/100700999/220933237-12f5983a-4ccd-467a-9f01-8f41d3e3178c.png)

## Home link broken in Samples page

In the samples page there's a [link back to the home page](https://github.com/dniccum/nova-documentation/blob/f8b488d6ac23e5ef2c0d58f790f8ee10ec4cba66/resources/documentation/sample.md?plain=1#L14) clicking that hits a 404 (at `/documentation/home`)

## Workaround?

Changing `nova.path` from `'/'` to  an empty string `''` fixes _some_ of these issues, but ideally the package should handle URIs better.

**Comment by dm-pf** [comment]
@dniccum I am not sure that PR #27 by itself solves the entirety of what this ticket reports. Appreciated the quick action though!

**Comment by dniccum** [comment]
@dm-pf Ok thanks for the update. I will have some time today to dive into this a bit further.

**Comment by dniccum** [comment]
@dm-pf Please review the [most recent release](https://github.com/dniccum/nova-documentation/tree/v3.1.4) to see if this fixes your issue.

**Comment by dm-pf** [comment]
@dniccum most recent release fixes most of the issues indeed. https://github.com/dniccum/nova-documentation/issues/28 is still broken though, I'll submit a PR in a few minutes to properly fix that.

**Comment by dniccum** [comment]
This has been fixed with #34
