### ISSUE TITLE
Escape periods in "replaceLinks" function

### ISSUE THREAD

**Issue by calvinps** [dniccum/nova-documentation#6]
In the `MarkdownUtility` class, the function `replaceLinks` has the following line:

`$output = preg_replace("/(\.md|.text|.mdown|.mkdn|.mkd|.mdwn|mdtxt|.Rmd|.mdtext)/i",'"',$output);`

but only the first period is escaped. For me, this caused several places in my content where the word "text" (not a file extension) was used to be replaced with just a double quote. Adding in backslashes before every period fixed the bug.

**Comment by dniccum** [comment]
Thanks for the addition. [PR has been merged and released](https://github.com/dniccum/nova-documentation/tree/v1.0.2.2).
