### ISSUE TITLE
Responsive sidebar

### ISSUE THREAD

**Issue by grikomsn** [dniccum/nova-documentation#8]
Since the sidebar is not responsive, layouts are overflowing and does not look good on small windows or mobile devices (screenshot below):

![image](https://user-images.githubusercontent.com/8220954/62835344-9a79fe00-bc81-11e9-8417-0ae9657fde57.png)

I am not familiar with Tailwind and modifying packages, but is there anyway that I can make the sidebar to move above the documentation?

**Comment by dniccum** [comment]
By default the Nova Dashboard is not responsive. Based on the screenshots that you have provided, I am assuming that you are using the [responsive theme](https://novapackages.com/packages/gregoriohc/laravel-nova-theme-responsive). This package's interface has not been designed, at least currently anyways, to have responsive behaviors.

I will tag this issue as a feature request.

**Comment by grikomsn** [comment]
Thanks for the response. True, I forgot to mention that I use the responsive theme. In the meantime, I'll try experimenting and maybe create a PR in the future.

**Comment by dniccum** [comment]
Just published a new release that adds a responsive layout that will work in the responsive theme. Please see [version 1.1.0](https://github.com/dniccum/nova-documentation/releases/tag/v1.1.0)
